site_name: ELVA
nav:
  - Welcome: index.md
  - User Guide: user-guide.md
  - Server Guide: server-guide.md
  - App Guide: app-guide.md
  - Developer Guide: developer-guide.md
  - Reference:
      - "reference/index.md"
      - Apps:
          - "reference/apps/index.md"
          - Editor: reference/apps/editor.md
          - Chat: reference/apps/chat.md
          - Service: reference/apps/service.md
          - Server: reference/apps/server.md
          - Drive: reference/apps/drive.md
      - Widgets:
          - "reference/widgets/index.md"
          - TextArea: reference/widgets/textarea.md
          - Config: reference/widgets/config.md
          - Status: reference/widgets/status.md
          - Screens: reference/widgets/screens.md
      - CLI: reference/cli.md
      - CLI Utils: reference/utils.md
      - Click Utilities: reference/click-utils.md
      - Click Lazy Loading Group: reference/click-lazy-group.md
      - Component: reference/component.md
      - Authentication: reference/auth.md
      - Server: reference/server.md
      - Provider: reference/provider.md
      - Store: reference/store.md
      - Renderer: reference/renderer.md
      - Protocol: reference/protocol.md
      - Parser: reference/parser.md
      - Log: reference/log.md
  - Changelog: changelog.md
  - Stories: stories/index.md
extra:
  generator: false
extra_css:
  - css/extra.css
  - css/mkdocstrings.css
#hooks:
  #  - scripts/generate_section_index.py
watch:
  - src/elva
theme:
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - toc.integrate
    - content.code.copy
  name: material
  favicon: img/logo.svg
  logo: img/logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: elva-light 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: elva-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - blog:
      blog_dir: stories
      blog_toc: true
      post_url_format: "{slug}"
      post_readtime: false
      archive: false
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true
            # docstring_options:
            #   ignore_init_summary: true
            merge_init_into_class: true
            members_order: source
            docstring_section_style: list
            # exclude private methods and attributes
            filters: ["!^_[\\s]+"]
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
